### ISSUE TITLE
FTS installation overwrites existing config

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTAKHub-Installation#1]
when installing new fts instance the config should be iterated over line by line and new parameters should be added as necessary to maintain existing configuration.

**Comment by jonaugustine** [comment]
@naman108 

I have an idea:
The person who is executing the role perhaps should be given the option to choose between: 

1. A complete overwrite of an existing configuration. This may be good for the case of a new install of FreeTAKServer.
2. Maintain the current configuration and (as you mention) add new parameters as necessary.

In _any_ case, a copy of the configuration should be made before any changes to the configuration.

**Comment by jonaugustine** [comment]
It seems like templating doesn't override:

**Comment by brothercorvo** [comment]
I vote for option 2.
