### ISSUE TITLE
terraform does not install on Pi4

### ISSUE THREAD

**Issue by pinztrek** [FreeTAKTeam/FreeTAKHub-Installation#12]
pi4, ubuntu 64 server 20.04 scratch install from official ubuntu image. 

++ sudo apt-get install terraform
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package terraform

Same issue following hashicorp instructions:

curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install terraform

Hit:1 https://apt.releases.hashicorp.com focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ppa.launchpad.net/ansible/ansible/ubuntu focal InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package terraform

Looks like it is not finding the pkg in the repo. There is an amd64 binary that can be downloaded. 
I have a log of the run if needed. 

Note that ubuntu dist image does an unattended upgrade at 1st boot apparantly, which I had to let complete.

**Comment by brothercorvo** [comment]
we do not support terraform on a PI
