### ISSUE TITLE
script fails to set passwordless

### ISSUE THREAD

**Issue by pinztrek** [FreeTAKTeam/FreeTAKHub-Installation#13]
typo in script, line 10, the echo should not have a colon

echo: 'Add passwordless Terraform and Ansible execution for the current user'
scripts/setup-Ansible.sh: line 10: echo:: command not found
++ LINE='ubuntu ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook,/usr/bin/terraform'
++ FILE=/etc/sudoers.d/dont-prompt-ubuntu-for-sudo-password
++ grep -qF -- 'ubuntu ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook,/usr/bin/terraform' /etc/sudoers.d/dont-prompt-ubuntu-for-sudo-password
grep: /etc/sudoers.d/dont-prompt-ubuntu-for-sudo-password: Permission denied
++ echo 'ubuntu ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook,/usr/bin/terraform'
scripts/setup-Ansible.sh: line 14: /etc/sudoers.d/dont-prompt-ubuntu-for-sudo-password: Permission denied
++ set +x

Even with the typo corrected the script does not create passwdless login. appears not to copy the file. 

The final error is because the file does not exist

**Comment by WaaromZoMoeilijk** [comment]
How are you running this command, as what user with which permissions?

**Comment by brothercorvo** [comment]
@HeroesLament can we reproduce this?

**Comment by HeroesLament** [comment]
I can certainly run a staging build today to see what happens.
