### ISSUE TITLE
One too many..

### ISSUE THREAD

**Issue by CallumMcEwen** [FreeTAKTeam/FreeTAKHub-Installation#16]
Simple issue. One too many '.' in the install.sh script

`ansible-playbook -u root -i localhost, --connection=local ../install_all.yml`

should be

`ansible-playbook -u root -i localhost, --connection=local ./install_all.yml`

Also, as all scripts are now in the 'scripts' directory, and not the root, the execution instruction from the root directory should be `./scripts/install.sh`

**Comment by WaaromZoMoeilijk** [comment]
https://github.com/FreeTAKTeam/FreeTAKHub-Installation/pull/19
https://github.com/FreeTAKTeam/FreeTAKHub-Installation/pull/20

**Comment by jonaugustine** [comment]
fixed with #20
