### ISSUE TITLE
README.md typos?

### ISSUE THREAD

**Issue by mighkel** [FreeTAKTeam/FreeTAKHub-Installation#24]
Under "**Checking Your Installation**" -> "**Node Red**" section, it reads `http://[YOURIP]::_8081_/`
As a result of the zero-touch install, my Node Red settings.js file identifies the UI port as _1880_, not 8081.
Also, each of the installation check code blocks includes a double ":", or "::" between the [IP] and the port #.  If that's normal, cool.

**Comment by jonaugustine** [comment]
fixed
