### ISSUE TITLE
Service name consistency

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTAKHub-Installation#25]
change the current name of the services from

- FreeTAKServer.service
- FreeTAKServerUI.service
- rtsp-simple-server.service
- nodered.service
- webmap.service

to

- Freetakserver.service
- Freetakserver-ui.service
- freetakhub-video.service
- freetakhub-nodered.service
- freetakhub-webmap.service

Mumble would be 
freetakhub-voice.service

**Comment by jonaugustine** [comment]
current services are:

```
fts.service
fts-ui.service
webmap.service
nodered.service
rtsp-simple-server.service
mumble-server.service
```

**Comment by logikal** [comment]
the current service names are great. I vote for leaving as is and closing.
