### ISSUE TITLE
FTS Zero Touch installation fails

### ISSUE THREAD

**Issue by lomfs24** [FreeTAKTeam/FreeTAKHub-Installation#31]
FTS installed using Zero Touch install script. Desktop computer, Quad-Core Intel chip, 8GB ram, fresh install of Ubuntu 20.04 updated to current with update and upgrade. 
Ran the script to install FTS with Zero Touch as instructed on the github.io page. Install failed at the portion it install pip.  Issue was resolved with exiting the installation process, installing pip manually, and re-running the install script. Second time, install proceeded normally.

**Comment by brothercorvo** [comment]
@lomfs24 so you says Pip installation failed? what is the error exactly?

**Comment by juneseptaugust** [comment]
assumed fixed by #33

**Comment by lomfs24** [comment]
I don't remember what the exact error was. Something to the effect that PIP failed to install. I installed pip manually, and the installation worked from there. In recent installs, I haven't tried it again. I just routinely install pip first.
