### ISSUE TITLE
Unbound variable on easy_install

### ISSUE THREAD

**Issue by JZNT** [FreeTAKTeam/FreeTAKHub-Installation#40]
Running easy_install.sh (or advanced install) on fresh Ubuntu 20.04 fails on

https://github.com/FreeTAKTeam/FreeTAKHub-Installation/blob/ccf8daeff37ecd1ee1b8302c02f6fc9cec7f41dc/scripts/easy_install.sh#L163

```
sudo scripts/easy_install.sh 
Checking if this script is running as root...Success!
scripts/easy_install.sh: line 163: SKIP: unbound variable
```

**Comment by janseptaugust** [comment]
fixed
