### ISSUE TITLE
Services should bind to 0.0.0.0

### ISSUE THREAD

**Issue by logikal** [FreeTAKTeam/FreeTAKHub-Installation#49]
Looking for thoughts here, before I go coding it all up:

Some services bind ports on 0.0.0.0, which I think is good.
Some services bind ports on the NIC's IP address (e.g. 192.168.1.4). murmur, rstp-simple-server, some FTS ports do this

If someone is using zerotier or another type of VPN, which is commonly documented and adopted in the community, only some of the services will work. I think all of the services should listen on 0.0.0.0 to reduce troubleshooting needs.

There's a problem here though; afaik FTS config needs an actual IP to advertise for datapackages. I think using the RFC1918 address (10.x.x.x, 192.168.x.x, 172.16.x.x.) as the default for that configuration should be the default, and we can document needing to update that for anyone using a VPN/mesh.

Thoughts?

**Comment by thesle3p** [comment]
can confirm this breaks installing in AWS

**Comment by janseptaugust** [comment]
I just pushed a change for it to bind to 0.0.0.0

**Comment by brothercorvo** [comment]
we reverted to the public IP for most compatibility in 1.9.9.5 Public

**Comment by thesle3p** [comment]
> we reverted to the public IP for most compatibility in 1.9.9.5 Public

confirmed everything works with the public IP set on AWS except the simple RTSP server which I had to manually set to 0.0.0.0 to run
