### ISSUE TITLE
Services using wrong IP (zerotouch)

### ISSUE THREAD

**Issue by Mokusenshi** [FreeTAKTeam/FreeTAKHub-Installation#55]
When using zerotouch command on a fresh Digital Ocean droplet (ubuntu 20.04 (LTS) x64) it doesnt use the actual IPv4 address but installs it on 127.0.0.1. Only the Mumble server installs on/uses the actual IPv4 address. Are you aware of this problem or am I doing something wrong?
Thanks in advance for your reply!

**Comment by brothercorvo** [comment]
fixed in 1.9.9.5 Public (a part the UI that is still wrong)

**Comment by brothercorvo** [comment]
fixed
