### ISSUE TITLE
video checker is misconfigured during installation

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTAKHub-Installation#58]
the video checker flow is misconfigured upon installation

**Comment by HeroesLament** [comment]
Forgot to push this earlier this week but the NodeRED flow "Post Video to FTS" has been fixed. Previously, the flow pointed to the rtsp-simple server on TCP port 9997, but the API endpoint /ManageVideoStream/postVideoStream referenced lives on the FTS API on port 19023. I also added in the default bearer token for the admin account, "token". This should be revised later with a dynamically created API token AND password for the admin account.
