### ISSUE TITLE
FTS hub installation - error in nodered component

### ISSUE THREAD

**Issue by enzomaximo** [FreeTAKTeam/FreeTAKHub-Installation#62]
The install fail because ansible.errors.AnsibleUndefinedVariable: 'videoserver_public_ipv4' is undefined 

Is right to put the variable in advanced_install.sh line 471? I tested this solution, the install go on, the server start and I have the login url, but the task TASK [nodered : Import Node-RED flows via HTTP POST] fail.

**Comment by HeroesLament** [comment]
Hello Enzo,

The advanced_install.sh installer currently is broken and it's on our roadmap to review all the variables and scope them appropriately for specific Ansible roles. In the meantime, can you use the easy_install.sh instead?

Thank you,

**Comment by brothercorvo** [comment]
@HeroesLament is this still actual?

**Comment by brothercorvo** [comment]
closing for now
