### ISSUE TITLE
Lost nodered node

### ISSUE THREAD

**Issue by enzomaximo** [FreeTAKTeam/FreeTAKHub-Installation#63]
Dear All,
after install FreeTAK from easy install, bordered flow have error (unknown node)  about the node world map. I install manually the node world map (node-red-contrib-web-worldmap)  and after the error about worldmap is deleted, but compare the same error on  config node. I install manually config node (node-red-contrib-config) and error delete, but the same error compare on ui_form node. I install (node-red-dashboard) and now all is ok, I hope.

**Comment by brothercorvo** [comment]
It looks like the dependencies are not installed correctly @HeroesLament

**Comment by brothercorvo** [comment]
this is fixed in the current version of the ZTI
