### ISSUE TITLE
Fix ZT Installer SystemD Unit File

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTAKHub-Installation#64]

**Comment by brothercorvo** [comment]
@HeroesLament is this still relevant?

**Comment by HeroesLament** [comment]
Unit file is about as clean as I can get it, and renamed the unit itself from fts to freetakserver and fts-ui to freetakserver-ui. This is to dis-ambiguate with the Linux core tool fts.

Need to discuss PID tracking options with Ghosty to more cleanly track the FTS process with Systemd.
