### ISSUE TITLE
push webmap flow in a separate Tab

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTAKHub-Installation#68]
the "SALUTE" TAB contains also the flow for the webmap, this is confusing
Instead we should create a dedicated tab for the webmap
![image](https://user-images.githubusercontent.com/60719165/196976288-cfa1a23a-0ab2-4dd1-86b7-a41a83379f9b.png)

**Comment by HeroesLament** [comment]
Webbmap has now properly been separated into its own tab. In addition, the process to upload flows to NodeRED now will not overwrite any additional flows users have on their servers.
